Updating debian package files
Updated license file, but generally this package cannot be used due to
unlicensed files

Change-Id: I470ce1c6b97d6e2319a7e77bd46b0ac27054366e

diff --git a/debian/adminbot.postinst b/debian/adminbot.postinst
--- a/debian/adminbot.postinst
+++ b/debian/adminbot.postinst
@@ -1,38 +1,73 @@
 #!/bin/sh
+# postinst script for adminbot
+#
+# see: dh_installdeb(1)
 
 set -e
 
-if ! getent group adminbot >/dev/null
-then
-	echo Adding group: adminbot
-	addgroup --system adminbot
-fi
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-if ! getent passwd adminbot >/dev/null
-then
-	echo Adding system user: adminbot
-	adduser --system --ingroup adminbot --home /var/lib/adminbot --shell /bin/false --no-create-home adminbot
-	usermod -c "Adminbot IRC logging sofware" adminbot
-fi
 
-if [ -d /var/lib/adminbot ]
-then
-	chown -R adminbot:adminbot /var/lib/adminbot
-	chmod 750 /var/lib/adminbot
-fi
+case "$1" in
+  configure)
+    if ! getent group adminbot >/dev/null
+    then
+      echo Adding group: adminbot
+      addgroup --system adminbot
+    fi
 
-if [ -d /etc/adminbot ]
-then
-	chown -R root:adminbot /etc/adminbot
-	chmod -R 750 /etc/adminbot
-fi
+    if ! getent passwd adminbot >/dev/null
+    then
+      echo Adding system user: adminbot
+      adduser --system --ingroup adminbot --home /var/lib/adminbot --shell /bin/false --no-create-home adminbot
+      usermod -c "Adminbot IRC logging sofware" adminbot
+    fi
 
-if [ -d /usr/lib/adminbot ]
-then
-	chown -R adminbot:adminbot /usr/lib/adminbot
-	chmod 755 /usr/lib/adminbot
-	chmod 755 /usr/lib/adminbot/adminlogbot.py
-	chmod 644 /usr/lib/adminbot/adminlog.py
-	chmod 644 /usr/lib/adminbot/statusnet.py
-	chmod 644 /usr/lib/adminbot/README
-fi
+    if [ -d /var/lib/adminbot ]
+    then
+      chown -R adminbot:adminbot /var/lib/adminbot
+      chmod 750 /var/lib/adminbot
+    fi
+
+    if [ -d /etc/adminbot ]
+    then
+      chown -R root:adminbot /etc/adminbot
+      chmod -R 750 /etc/adminbot
+    fi
+
+    if [ -d /usr/lib/adminbot ]
+    then
+      chown -R adminbot:adminbot /usr/lib/adminbot
+      chmod 755 /usr/lib/adminbot
+      chmod 755 /usr/lib/adminbot/adminlogbot.py
+      chmod 644 /usr/lib/adminbot/adminlog.py
+      chmod 644 /usr/lib/adminbot/statusnet.py
+      chmod 644 /usr/lib/adminbot/README
+    fi
+    ;;
+
+  abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+  *)
+    echo "postinst called with unknown argument \`$1'" >&2
+    exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
diff --git a/debian/adminbot.postrm b/debian/adminbot.postrm
--- a/debian/adminbot.postrm
+++ b/debian/adminbot.postrm
@@ -1,15 +1,48 @@
 #!/bin/sh
+# postrm script for adminbot
+#
+# see: dh_installdeb(1)
 
-/usr/sbin/service adminbot stop
+set -e
 
-if getent passwd adminbot >/dev/null
-then
-	echo "Removing user: adminbot"
-	deluser adminbot
-fi
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-if getent group adminbot >/dev/null
-then
-	echo "Removing group: adminbot"
-	delgroup adminbot
-fi
+
+case "$1" in
+  purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    if getent passwd adminbot >/dev/null
+    then
+      echo "Removing user: adminbot"
+      deluser adminbot
+    fi
+
+    if getent group adminbot >/dev/null
+    then
+      echo "Removing group: adminbot"
+      delgroup adminbot
+    fi
+    ;;
+
+  *)
+    echo "postrm called with unknown argument \`$1'" >&2
+    exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
